// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEMBS9EDA0Fb0IkSz6li0Ga-IIZ-CNMao',
    appId: '1:77684496214:web:5f4f98d7cb4d93b226a8f7',
    messagingSenderId: '77684496214',
    projectId: 'pet-shop-demo-48c60',
    authDomain: 'pet-shop-demo-48c60.firebaseapp.com',
    storageBucket: 'pet-shop-demo-48c60.appspot.com',
    measurementId: 'G-P7SMJNG0PF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD2oS6R3Q1MNPlWHv8lXLF43gTmssTLAo',
    appId: '1:77684496214:android:c431830641e54dcf26a8f7',
    messagingSenderId: '77684496214',
    projectId: 'pet-shop-demo-48c60',
    storageBucket: 'pet-shop-demo-48c60.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNA8nJioe4pccbLzIEFqQIR2ByAAmjqZ0',
    appId: '1:77684496214:ios:257ccab47d94d90c26a8f7',
    messagingSenderId: '77684496214',
    projectId: 'pet-shop-demo-48c60',
    storageBucket: 'pet-shop-demo-48c60.appspot.com',
    iosBundleId: 'com.chinhnc.petShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNA8nJioe4pccbLzIEFqQIR2ByAAmjqZ0',
    appId: '1:77684496214:ios:429843881ef65a0726a8f7',
    messagingSenderId: '77684496214',
    projectId: 'pet-shop-demo-48c60',
    storageBucket: 'pet-shop-demo-48c60.appspot.com',
    iosBundleId: 'com.chinhnc.petShop.RunnerTests',
  );
}
